services:
  vpn-back:
    build:
      context: ./vpn-back
    ports:
      - "5050:5050"
    env_file:
      - ./vpn-back/.env
    environment:
      SSH_KEY_PATH: /run/secrets/vpnctl_ed25519
      SSH_USER: vpnctl
    volumes:
      - ./vpnctl_ed25519:/run/secrets/vpnctl_ed25519:ro

